sequenceDiagram
  participant participant_assertUniqueIds as assertUniqueIds
  participant participant_createGraph as createGraph
  participant participant_reverseGraph as reverseGraph
  participant_reverseGraph->>participant_createGraph: createGraph()
  participant_createGraph->>participant_assertUniqueIds: assertUniqueIds()
  participant_assertUniqueIds-->>participant_createGraph: return
  participant_createGraph-->>participant_reverseGraph: return
